name: Attach release artifacts

on:
  push:
    tags:
      - '*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: checkout master
        uses: actions/checkout@master

      - name: attach release artifacts
        uses: sestus/golang-attach-release-artifacts-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          go_files: 'cmd/godaddy-dyndns/main.go cmd/public-ip-getter/main.go'
          binaries: 'godaddy-dyndns public-ip-getter'